'use strict';

let browseFilters = {q:'',category:'all',mode:'all',sort:'recommended'};
function createSurveyState() { return {step:-1,answers:['','','',[],''],complete:false}; }
const surveySessions = {home:createSurveyState(),feedback:createSurveyState()};
let activeSurvey = 'home';
let uploadPhoto = '';
const SURVEY_QUESTIONS = [
  {text:'What’s your occupation?',type:'text',optional:true,hint:'A short description is enough.',placeholder:'For example, teacher, designer, or student'},
  {text:'What email address can we use to contact you about the project?',type:'email',optional:true,hint:'Leave this blank if you prefer not to be contacted.',placeholder:'you@example.com'},
  {text:'How would you like to use the platform?',type:'radio',options:['Borrow or rent items','Share or rent out my items','Both','I’m just exploring']},
  {text:'What would motivate you to use the platform?',type:'checkbox',hint:'Choose all that apply.',options:['Save money','Use something without buying it','Make better use of items I own','Reduce waste','Connect with other people','Other']},
  {text:'What would make this platform more useful or trustworthy for you?',type:'textarea',optional:true,hint:'Share any suggestions, concerns, or features you would like to see.',placeholder:'Your thoughts and ideas…'}
];

function categoryOptions(selected) { return CATEGORIES.map(c=>`<option value="${c.id}" ${c.id===selected?'selected':''}>${c.name}</option>`).join(''); }
function pageIntro(eyebrow,title,description,action='') { return `<section class="page-intro"><div class="container page-intro-row"><div><p class="eyebrow">${eyebrow}</p><h1>${title}</h1><p>${description}</p></div>${action}</div></section>`; }
function emptyState(symbol,title,text,link='browse',label='Find an item') { return `<div class="empty-state">${icon(symbol)}<h2>${title}</h2><p>${text}</p><a class="button button-primary" href="#/${link}">${label}</a></div>`; }

views.browse = current => {
  browseFilters={q:current.params.get('q')||'',category:current.params.get('category')||'all',mode:'all',sort:'recommended'};
  return `${pageIntro('Borrow for free. Rent for a little.','Find an item.','Choose a category, search for an item, and arrange the details with its owner.')}
    <section class="page-content"><div class="container">
      <div class="filter-chips" aria-label="Item categories">
        <button class="filter-chip ${browseFilters.category==='all'?'active':''}" data-action="filter-category" data-id="all" aria-pressed="${browseFilters.category==='all'}">${icon('grid')}<span>All items</span></button>
        ${CATEGORIES.map(c=>`<button class="filter-chip ${browseFilters.category===c.id?'active':''}" data-action="filter-category" data-id="${c.id}" aria-pressed="${browseFilters.category===c.id}">${icon(c.icon)}<span>${c.name}</span></button>`).join('')}
      </div>
      <div class="browse-toolbar">
        <div class="browse-search">${icon('search')}<label class="sr-only" for="browse-query">Search items</label><input id="browse-query" type="search" placeholder="Search for a camera, a drill, a mug…" value="${esc(browseFilters.q)}"></div>
        <label class="sr-only" for="price-filter">Sharing type</label><select id="price-filter"><option value="all">Free & paid</option><option value="free">Free to borrow</option><option value="paid">Paid rentals</option></select>
        <label class="sr-only" for="sort-filter">Sort items</label><select id="sort-filter"><option value="recommended">Recommended</option><option value="low">Price: low to high</option><option value="high">Price: high to low</option><option value="name">Name: A to Z</option></select>
      </div>
      <div class="results-line"><span id="result-count" aria-live="polite">${filteredItems().length} ${filteredItems().length===1?'item':'items'} to explore</span><span class="sample-note">Example listings, dates & pickup points</span></div>
      <div class="cards" id="browse-results">${browseResults()}</div>
      <div class="browse-request-note"><p>Can’t find what you need?</p><a class="text-link" href="#/requests">Post a community request</a></div>
    </div></section>`;
};
function filteredItems() {
  let result=items().filter(item=>(browseFilters.category==='all'||item.category===browseFilters.category)&&(browseFilters.mode==='all'||(browseFilters.mode==='free'?Number(item.price)===0:Number(item.price)>0))&&`${item.title} ${item.description} ${category(item.category).name}`.toLowerCase().includes(browseFilters.q.toLowerCase().trim()));
  if(browseFilters.sort==='low')result.sort((a,b)=>a.price-b.price);
  if(browseFilters.sort==='high')result.sort((a,b)=>b.price-a.price);
  if(browseFilters.sort==='name')result.sort((a,b)=>a.title.localeCompare(b.title));
  return result;
}
function browseResults() { const results=filteredItems();return results.length?results.map(card).join(''):`<div class="empty-state">${icon('search')}<h2>No matches just yet.</h2><p>Try another word, clear a filter, or ask the community for what you need.</p><button class="button button-secondary" data-action="clear-filters">Clear filters</button> <a class="button button-primary" href="#/requests">Request an item</a></div>`; }
function updateBrowse() { document.getElementById('browse-results').innerHTML=browseResults();document.getElementById('result-count').textContent=`${filteredItems().length} ${filteredItems().length===1?'item':'items'} to explore`; }
views.saved = () => `${pageIntro('Your little collection','Useful things worth keeping.','Tap the heart on anything you like. Your saved items will be waiting here.')}<section class="page-content"><div class="container"><div class="cards">${state.saved.length?items().filter(item=>state.saved.includes(item.id)).map(card).join(''):emptyState('heart','Nothing saved, yet.','Find something you like and give it a heart. It’s an easy way to keep track while you explore.')}</div></div></section>`;
views.item = current => {
  const item=getItem(current.id);if(!item)return `${pageIntro('A small detour','We couldn’t find that item.','It may have been removed from this preview.')}<section class="page-content"><div class="container">${emptyState('search','Find another useful thing.','There are more items to explore.')}</div></section>`;
  const saved=state.saved.includes(item.id);
  return `<div class="container"><div class="breadcrumb"><a href="#/browse">Find an item</a><span>/</span><a href="#/browse?category=${item.category}">${category(item.category).name}</a></div><section class="detail-grid page-content"><div><img class="detail-image" src="${imageUrl(item)}" alt="${esc(item.title)}" width="900" height="775"><p class="detail-photo-note">Example item · Photos illustrate the sharing concept.</p></div><div class="detail-copy"><div class="detail-topline"><span>${category(item.category).name}</span><button class="icon-button" data-action="save" data-id="${esc(item.id)}" aria-label="${saved?'Unsave':'Save'} ${esc(item.title)}" aria-pressed="${saved}">${icon('heart')}</button></div><h1>${esc(item.title)}</h1><div class="detail-price">${price(item)} <small>${item.price?'per day':'to borrow'}</small></div><span class="condition-pill">${esc(item.condition)}</span><p class="form-note">Availability: ${esc(item.dates || 'Example available dates')}</p><p class="detail-description">${esc(item.description)}</p><form class="rental-box" id="rental-form" data-id="${esc(item.id)}"><div class="field-grid"><div class="field"><label for="borrow-from">Borrow from</label><input id="borrow-from" name="from" placeholder="Example start date" maxlength="60"></div><div class="field"><label for="borrow-until">Return by</label><input id="borrow-until" name="until" placeholder="Example return date" maxlength="60"></div></div><div class="field"><label for="pickup-point">Pickup & return</label><input id="pickup-point" name="location" value="${esc(item.location || '')}" placeholder="Example pickup point" maxlength="100"></div><div class="total-line"><span>${item.price?'Example rental rate':'Sharing arrangement'}</span><strong>${item.price?price(item)+' / day':'Free to borrow'}</strong></div><button class="button button-primary button-full" type="submit">${icon('message')}Message ${esc(item.owner)}</button><p class="form-note" style="margin:12px 0 0">Agree on your dates and handover with the owner. This preview uses example dates and places.</p></form><div class="detail-owner"><div class="owner-row">${avatar(item.owner,item.initials)}<div><strong>Shared by ${esc(item.owner)}</strong><small>Example owner</small></div></div><a class="text-link" href="#/messages?item=${encodeURIComponent(item.id)}">Say hello</a></div></div></section></div>`;
};
views.share = () => {
  uploadPhoto='';
  return `${pageIntro('Offer what you own','Share an item.','List your own things for free sharing or paid rental. You choose how to offer them.')}<section class="page-content"><div class="container form-layout"><form class="form-panel" id="share-form"><h2>Tell us about your item.</h2><div class="upload-field">${icon('upload')}<div><label for="item-photo">Add a photo</label><input id="item-photo" type="file" accept="image/jpeg,image/png,image/webp"><small>Optional · JPG, PNG or WebP · up to 2 MB. A category photo is used if you skip this.</small></div><img id="upload-preview" class="image-upload-preview" alt="Your selected item photo" hidden></div><div class="field"><label for="item-title">Item name</label><input id="item-title" name="title" placeholder="For example, a compact cordless drill" required maxlength="80"></div><div class="field-grid"><div class="field"><label for="item-category">Category</label><select id="item-category" name="category">${categoryOptions('kitchen')}</select></div><div class="field"><label for="item-condition">Condition</label><select id="item-condition" name="condition"><option>Good condition</option><option>Like new</option><option>Well used, works well</option></select></div></div><div class="field"><label for="item-description">A little about it</label><textarea id="item-description" name="description" placeholder="What is it useful for? What comes with it? Anything the borrower should know?" required maxlength="600"></textarea></div><p class="field-label" style="margin-bottom:12px">How would you like to share it?</p><div class="choice-grid"><label class="choice-card"><input type="radio" name="mode" value="free" checked><strong>Free to borrow</strong><small>A little community kindness.</small></label><label class="choice-card"><input type="radio" name="mode" value="paid"><strong>Paid rental</strong><small>Set your own daily price.</small></label></div><div class="field" id="rental-price-field" hidden><label for="item-price">Daily price (€)</label><input id="item-price" name="price" type="number" min="0.5" max="999" step="0.5" placeholder="For example, 4" disabled></div><div class="field-grid"><div class="field"><label for="item-dates">Availability</label><input id="item-dates" name="dates" placeholder="Example available dates" maxlength="80"></div><div class="field"><label for="item-location">Pickup location</label><input id="item-location" name="location" placeholder="Example pickup point" maxlength="100"></div></div><div class="notice">${icon('leaf')}<span>Your listing appears in this browser’s preview. No public listing is created.</span></div><p class="form-error" id="share-error" role="alert" hidden></p><div class="form-actions"><button class="button button-primary" type="submit">Publish demo listing</button><a class="button button-text" href="#/browse">Back to browsing</a></div></form></div></section>`;
};
views.requests = () => `${pageIntro('Ask for an item. Offer a little help.','Community requests.','Can’t find what you need? Post a request, or offer an item to someone who needs it.',`<button class="button button-primary" data-action="new-request">${icon('plus')}Post a request</button>`)}<section class="page-content"><div class="container"><div class="results-line"><span>${state.requests.length+SEED_REQUESTS.length} community requests</span><span class="sample-note">Example requests & pickup points</span></div><div class="request-cards">${[...state.requests,...SEED_REQUESTS].map(requestCard).join('')}</div><div class="notice" style="max-width:650px;margin-top:28px">${icon('message')}<span>Have something useful? Choose “I can help” to offer an item and open a demo conversation.</span></div></div></section>`;

function chatContext(current) {
  const item=getItem(current.params.get('item'));
  const req=[...state.requests,...SEED_REQUESTS].find(r=>r.id===current.params.get('request'));
  if(req)return {key:`request-${req.id}`,name:req.name,initials:req.initials,title:req.title,request:req};
  const fallback=item||SEED_ITEMS[0];return {key:fallback.id,name:fallback.owner,initials:fallback.initials,title:fallback.title,item:fallback};
}
views.messages = current => {
  const context=chatContext(current);
  const old=state.messages[context.key]||[];
  const greeting=context.request?`Hi! I’m looking for ${context.title.toLowerCase()}. Thanks for offering to help.`:`Hi! Happy to share this. Let me know when you’d like to borrow it, and we can arrange a pickup.`;
  const draft=state.rentalDraft && context.item && state.rentalDraft.id===context.item.id?`Hi ${context.name}, I’d like to borrow this from ${state.rentalDraft.from} until ${state.rentalDraft.until}. Could we meet at ${state.rentalDraft.location}?`:'';
  const conversations=[...new Set([context.key,...Object.keys(state.messages),'pot','drill','camera'])].map(key=>{
    const req=key.startsWith('request-')?[...state.requests,...SEED_REQUESTS].find(r=>`request-${r.id}`===key):null;
    const item=req?null:getItem(key);if(!req&&!item)return '';
    const name=req?req.name:item.owner;return `<a class="conversation-link ${key===context.key?'active':''}" href="#/messages?${req?'request='+encodeURIComponent(req.id):'item='+encodeURIComponent(item.id)}">${avatar(name,req?.initials||item?.initials)}<span><strong>${esc(name)}</strong><small>${esc(req?.title||item.title)}</small></span></a>`;
  }).join('');
  return `${pageIntro('Make a plan together','Talk to the owner.','Say hello, suggest dates, and arrange a pickup and return point.')}<section class="page-content"><div class="container"><div class="message-layout"><aside class="conversation-list"><h2>Your conversations</h2>${conversations}</aside><div class="chat-panel"><div class="chat-header"><div class="owner-row">${avatar(context.name,context.initials)}<div><strong>${esc(context.name)}</strong><small>Example ${context.request?'borrower':'owner'}</small></div></div><span class="preview-label">Demo conversation</span></div><a class="chat-item" href="#/${context.item?'item/'+encodeURIComponent(context.item.id):'requests'}">${context.item?`<img src="${imageUrl(context.item)}" alt="${esc(context.title)}">`:icon('message')}<div><strong>${esc(context.title)}</strong><small>${context.item?price(context.item)+(context.item.price?' / day':' to borrow'):'Community request'}</small></div></a><div class="chat-messages" id="chat-messages" aria-live="polite"><div class="chat-time">Conversation preview</div><div class="chat-bubble">${esc(greeting)}</div>${old.map(m=>`<div class="chat-bubble ${m.mine?'mine':''}">${esc(m.text)}</div>`).join('')}</div><form class="chat-composer" id="message-form" data-key="${esc(context.key)}"><label class="sr-only" for="message-input">Your message</label><input class="input" id="message-input" name="message" placeholder="Write a friendly hello…" maxlength="1000" value="${esc(draft)}" autocomplete="off" required><button class="button button-primary" type="submit">Send</button></form></div></div><p class="survey-note">This is a conversation with a fictional user. Messages stay in this browser.</p></div></section>`;
};

views['how-it-works'] = () => `${pageIntro('Borrow. Share. Repeat.','Good things are better shared.','A simple way to use what you need, and make more of what you own.')}<section class="section share-band"><div class="container share-band-grid"><div><h2>Find it.<br>Make a plan.<br>Give it another turn.</h2><p>Choose a free borrow or a paid rental. Agree on the details with the owner, and return the item after you’ve used it.</p><a class="button button-primary" href="#/browse">Find an item</a></div><div class="steps"><div class="step"><span class="step-number">01</span><div><h3>Explore useful things</h3><p>Search by name or category. Use the free and paid filters to find what suits you.</p></div></div><div class="step"><span class="step-number">02</span><div><h3>Talk to the owner</h3><p>Check the item details, suggest dates, and agree on a pickup and return point.</p></div></div><div class="step"><span class="step-number">03</span><div><h3>Look after it</h3><p>Use the item with care and return it as agreed, ready for someone else.</p></div></div></div></div></section><section class="section"><div class="container"><div class="section-heading"><div><p class="eyebrow">A few things you might wonder</p><h2>Sharing, made clearer.</h2></div></div><div class="faq-list"><details><summary>Can I borrow something for free?</summary><p>Yes. Owners choose whether an item is free to borrow or available for a paid rental. Every listing shows the arrangement clearly.</p></details><details><summary>Can I both borrow and share items?</summary><p>Absolutely. You can explore the listings and share your own things with the same profile.</p></details><details><summary>What if I can’t find what I need?</summary><p>Post a community request. Describe the item, add example dates, and let someone offer a suitable item.</p></details><details><summary>How do pickup and return work?</summary><p>You and the owner agree on the details in the conversation. This preview uses example dates and places so you can explore the flow.</p></details><details><summary>What can I try in this preview?</summary><p>You can save items, create demo listings and requests, offer an item, and try a conversation. These changes stay in your browser. Accounts, payments and real messages are not connected.</p></details></div></div></section>`;
function questionnaireSection(sessionName) {
  activeSurvey=sessionName;
  if(sessionName==='home')surveySessions.home=createSurveyState();
  return `<section class="questionnaire-section" aria-labelledby="questionnaire-heading"><div class="container home-survey-layout">
    <div class="questionnaire-intro"><p class="eyebrow">Community questionnaire</p><h2 id="questionnaire-heading">Help shape our community.</h2><p>What would you borrow? What could make sharing easier? Your ideas can help shape what comes next.</p></div>
    <div class="questionnaire-form"><div class="survey-wrap" id="survey-content">${surveyHTML()}</div></div>
  </div></section>`;
}
views.feedback = () => questionnaireSection('feedback');
function surveyHTML() {
  const session=surveySessions[activeSurvey];
  if(session.complete)return `<div class="survey-welcome">${icon('check')}<p class="eyebrow">That’s the whole preview.</p><h2>Thanks for sharing your thoughts.</h2><p>You’ve reached the end of the demo questionnaire. Your answers haven’t been sent.</p><a class="button button-primary" href="#/browse">Keep exploring</a><br><button class="button button-text" data-action="survey-restart">Try the questionnaire again</button></div>`;
  if(session.step<0)return `<div class="survey-welcome"><h2>Tell us what you think.</h2><p>A few questions about what you need, what you would share, and what could be better.</p><button class="button button-primary" data-action="survey-start">Start</button><p class="form-note">5 questions · About 2 minutes</p></div>`;
  const q=SURVEY_QUESTIONS[session.step];const answer=session.answers[session.step];
  let field='';
  if(q.type==='text'||q.type==='email')field=`<input class="input" id="survey-answer" name="answer" type="${q.type}" placeholder="${q.placeholder}" value="${esc(answer)}" maxlength="150" aria-label="${esc(q.text)}">`;
  if(q.type==='textarea')field=`<textarea class="input" id="survey-answer" name="answer" rows="4" placeholder="${q.placeholder}" maxlength="1500" aria-label="${esc(q.text)}">${esc(answer)}</textarea>`;
  if(q.options)field=q.options.map((option,i)=>`<label class="survey-option"><input type="${q.type}" name="answer" value="${esc(option)}" ${Array.isArray(answer)?answer.includes(option)?'checked':'':answer===option?'checked':''}>${option}</label>`).join('');
  return `<div class="survey-topline"><span>Question ${session.step+1} of 5</span><span>${q.optional?'Optional':'Required'}</span></div><form id="survey-form" data-session="${activeSurvey}" data-step="${session.step}"><h2 id="survey-question">${q.text}</h2>${q.hint?`<p>${q.hint}</p>`:''}<div class="field" role="group" aria-labelledby="survey-question">${field}</div><p class="form-error" id="survey-error" role="alert" hidden></p><div class="survey-progress" aria-hidden="true"><span style="width:${(session.step+1)*20}%"></span></div><div class="survey-actions"><button class="button button-text" type="button" data-action="survey-back">Back</button><button class="button button-primary" type="submit">${session.step===4?'Finish preview':q.optional?'Continue / skip':'Continue'}</button></div></form>`;
}
function updateSurvey() { const content=document.getElementById('survey-content');content.innerHTML=surveyHTML();content.querySelector('input,textarea,button,a')?.focus({preventScroll:true});content.scrollIntoView({block:'start',behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'}); }

function openAuth(tab='signin') {
  currentAuthTab=tab;
  const content=document.getElementById('auth-content');
  if(state.user)content.innerHTML=`<p class="eyebrow">Your corner</p><h2>Hello, ${esc(state.user.name)}.</h2><p>You’re exploring with a demo profile.</p><div class="form-actions"><a class="button button-primary" data-action="close-modal" href="#/messages">Open messages</a><button class="button button-secondary" data-action="signout">Sign out</button></div><div class="notice"><span>Want to explore from the beginning? Start fresh to clear the demo items, requests, conversations, and saved items in this browser.</span></div><button class="button button-text" data-action="reset-preview">Start fresh</button>`;
  else content.innerHTML=`<p class="eyebrow">All for one, one for all</p><h2>${tab==='signin'?'Welcome back.':'Make yourself at home.'}</h2><p>${tab==='signin'?'A useful thing is just around the corner.':'Borrow a little. Share a little.'}</p><div class="auth-tabs"><button class="${tab==='signin'?'active':''}" data-action="auth-tab" data-tab="signin">Sign in</button><button class="${tab==='signup'?'active':''}" data-action="auth-tab" data-tab="signup">Sign up</button></div><form id="auth-form">${tab==='signup'?'<div class="field"><label for="auth-name">Your name</label><input id="auth-name" name="name" placeholder="First name" maxlength="40" required autocomplete="off"></div>':''}<div class="field"><label for="auth-email">Email address</label><input id="auth-email" type="email" name="email" placeholder="you@example.com" required autocomplete="off"></div><div class="field"><label for="auth-password">Password</label><input id="auth-password" type="password" name="password" placeholder="Use any demo password" minlength="6" required autocomplete="off"></div><button class="button button-primary button-full" type="submit">${tab==='signin'?'Sign in to preview':'Create demo profile'}</button></form><div class="notice"><span>Sample content. No real account will be created.</span></div><button class="button button-text button-full" data-action="demo-login">Continue as Alex</button>`;
  const dialog=document.getElementById('auth-dialog');if(!dialog.open)dialog.showModal();
}
function openRequest() {
  document.getElementById('request-content').innerHTML=`<p class="eyebrow">Ask the community</p><h2>What could you use?</h2><p>Someone might have it sitting on a shelf.</p><form id="request-form"><div class="field"><label for="request-title">What are you looking for?</label><input id="request-title" name="title" placeholder="For example, a camera for the weekend" maxlength="80" required></div><div class="field"><label for="request-category">Category</label><select id="request-category" name="category">${categoryOptions('diy')}</select></div><div class="field"><label for="request-details">Tell us a little more</label><textarea id="request-details" name="description" placeholder="What do you need it for? Any details that could help?" required maxlength="600"></textarea></div><div class="field-grid"><div class="field"><label for="request-dates">When do you need it?</label><input id="request-dates" name="dates" placeholder="Example dates" maxlength="80"></div><div class="field"><label for="request-location">Where could you collect it?</label><input id="request-location" name="location" placeholder="Example pickup point" maxlength="100"></div></div><p class="form-note">Your request is added to this browser’s preview.</p><button class="button button-primary button-full" type="submit">Post demo request</button></form>`;
  document.getElementById('request-dialog').showModal();
}
function openOffer(id) {
  const request=[...state.requests,...SEED_REQUESTS].find(r=>r.id===id);if(!request)return;
  const previous=state.offers.find(o=>o.requestId===id);
  const matching=items().filter(item=>item.category===request.category);
  document.getElementById('offer-content').innerHTML=previous?`<p class="eyebrow">Your offer</p><h2>You offered a useful thing.</h2><p>For ${esc(request.name)}’s request: <strong>${esc(request.title)}</strong></p><div class="notice"><span>${esc(previous.description)}</span></div><a class="button button-primary button-full" data-action="close-modal" href="#/messages?request=${encodeURIComponent(id)}">Open demo conversation</a>`:`<p class="eyebrow">A little help goes a long way</p><h2>Have what ${esc(request.name)} needs?</h2><p>${esc(request.title)}</p><form id="offer-form" data-id="${esc(id)}"><div class="field"><label for="offer-item">Choose an example item</label><select id="offer-item" name="item"><option value="">I have something else</option>${matching.map(item=>`<option value="${item.id}">${esc(item.title)}</option>`).join('')}</select></div><div class="field"><label for="offer-description">Your offer</label><textarea id="offer-description" name="description" placeholder="Describe your item and how you could help…" required maxlength="600"></textarea></div><p class="form-note">This adds an offer to the demo request. Nothing is sent to a real person.</p><button class="button button-primary button-full" type="submit">Offer item & open chat</button></form>`;
  document.getElementById('offer-dialog').showModal();
}

document.addEventListener('input',event=>{
  if(event.target.id==='browse-query'){browseFilters.q=event.target.value;updateBrowse();}
});
document.addEventListener('change',event=>{
  if(event.target.id==='price-filter'){browseFilters.mode=event.target.value;updateBrowse();}
  if(event.target.id==='sort-filter'){browseFilters.sort=event.target.value;updateBrowse();}
  if(event.target.name==='mode'&&event.target.closest('#share-form')){const paid=event.target.value==='paid';document.getElementById('rental-price-field').hidden=!paid;document.getElementById('item-price').disabled=!paid;document.getElementById('item-price').required=paid;}
  if(event.target.id==='offer-item'&&event.target.value){const item=getItem(event.target.value);document.getElementById('offer-description').value=`I can offer my ${item.title.toLowerCase()}. Let’s agree on example dates and a pickup point.`;}
  if(event.target.id==='item-photo'){
    const file=event.target.files[0];const preview=document.getElementById('upload-preview');uploadPhoto='';preview.hidden=true;
    if(!file)return;if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>2*1024*1024){showToast('Choose a JPG, PNG or WebP photo under 2 MB.');event.target.value='';return;}
    const reader=new FileReader();reader.onload=()=>{uploadPhoto=reader.result;preview.src=uploadPhoto;preview.hidden=false;};reader.readAsDataURL(file);
  }
});
document.addEventListener('click',event=>{
  const button=event.target.closest('[data-action]');if(!button)return;
  const action=button.dataset.action;
  if(action==='filter-category'){browseFilters.category=button.dataset.id;document.querySelectorAll('[data-action="filter-category"]').forEach(b=>{const active=b.dataset.id===browseFilters.category;b.classList.toggle('active',active);b.setAttribute('aria-pressed',String(active));});updateBrowse();}
  if(action==='clear-filters'){browseFilters={q:'',category:'all',mode:'all',sort:'recommended'};document.getElementById('browse-query').value='';document.getElementById('price-filter').value='all';document.getElementById('sort-filter').value='recommended';document.querySelectorAll('[data-action="filter-category"]').forEach(b=>{const active=b.dataset.id==='all';b.classList.toggle('active',active);b.setAttribute('aria-pressed',String(active));});updateBrowse();}
  if(action==='auth')openAuth();
  if(action==='auth-tab')openAuth(button.dataset.tab);
  if(action==='signout'){state.user=null;saveState();document.getElementById('auth-dialog').close();showToast('Signed out of the demo profile.');}
  if(action==='reset-preview'){state={saved:[],items:[],requests:[],offers:[],messages:{},user:null};surveySessions.home=createSurveyState();surveySessions.feedback=createSurveyState();saveState();document.getElementById('auth-dialog').close();navigate('');showToast('A fresh preview, ready to explore.');}
  if(action==='demo-login'){state.user={name:'Alex'};saveState();document.getElementById('auth-dialog').close();showToast('Welcome, Alex. You’re exploring with a demo profile.');}
  if(action==='new-request')openRequest();
  if(action==='offer')openOffer(button.dataset.id);
  if(action==='survey-start'){surveySessions[activeSurvey].step=0;updateSurvey();}
  if(action==='survey-back'){captureSurvey(document.getElementById('survey-form'));surveySessions[activeSurvey].step--;updateSurvey();}
  if(action==='survey-restart'){surveySessions[activeSurvey]=createSurveyState();updateSurvey();}
});
function captureSurvey(form) {
  if(!form)return;
  const session=surveySessions[form.dataset.session];const step=Number(form.dataset.step);
  if(!session||session.complete||step!==session.step||!SURVEY_QUESTIONS[step])return;
  const data=new FormData(form);
  session.answers[step]=SURVEY_QUESTIONS[step].type==='checkbox'?data.getAll('answer'):(data.get('answer')||'');
}
document.addEventListener('submit',event=>{
  const form=event.target;
  if(form.id==='auth-form'){event.preventDefault();const data=new FormData(form);state.user={name:currentAuthTab==='signup'?data.get('name').trim():'Alex'};saveState();form.reset();document.getElementById('auth-dialog').close();showToast(`Welcome, ${state.user.name}. This is your demo profile.`);}
  if(form.id==='rental-form'){event.preventDefault();const data=new FormData(form);state.rentalDraft={id:form.dataset.id,from:data.get('from').trim()||'Example start date',until:data.get('until').trim()||'Example return date',location:data.get('location').trim()||'Example pickup point'};saveState();navigate(`messages?item=${encodeURIComponent(form.dataset.id)}`);}
  if(form.id==='share-form'){
    event.preventDefault();const data=new FormData(form);const title=data.get('title').trim();const description=data.get('description').trim();const error=document.getElementById('share-error');if(!title||!description){error.textContent='Add an item name and a short description.';error.hidden=false;return;}
    const id='item-'+Date.now();const cat=category(data.get('category'));state.items.unshift({id,title,description,category:cat.id,image:cat.image,photo:uploadPhoto,price:data.get('mode')==='paid'?Number(data.get('price')):0,condition:data.get('condition'),dates:data.get('dates').trim()||'Example available dates',location:data.get('location').trim()||'Example pickup point',owner:state.user?.name||'You',initials:(state.user?.name||'You').slice(0,2).toUpperCase()});saveState();navigate(`item/${id}`);showToast('Your demo listing is ready to explore.');
  }
  if(form.id==='request-form'){event.preventDefault();const data=new FormData(form);const title=data.get('title').trim();const description=data.get('description').trim();if(!title||!description){showToast('Add a request title and a short description.');return;}const name=state.user?.name||'You';state.requests.unshift({id:'request-'+Date.now(),title,description,category:data.get('category'),dates:data.get('dates').trim()||'Example dates',location:data.get('location').trim()||'Example pickup point',name,initials:name.slice(0,2).toUpperCase()});saveState();document.getElementById('request-dialog').close();if(route().name==='requests')render();else navigate('requests');showToast('Your demo request has been added.');}
  if(form.id==='offer-form'){event.preventDefault();const data=new FormData(form);const description=data.get('description').trim();if(!description){showToast('Describe what you can offer.');return;}const key='request-'+form.dataset.id;state.offers.push({requestId:form.dataset.id,description,item:data.get('item')});state.messages[key]=[...(state.messages[key]||[]),{mine:true,text:description}];saveState();document.getElementById('offer-dialog').close();navigate(`messages?request=${encodeURIComponent(form.dataset.id)}`);showToast('Your offer has been added to this demo conversation.');}
  if(form.id==='message-form'){
    event.preventDefault();const text=new FormData(form).get('message').trim();if(!text)return;const key=form.dataset.key;state.messages[key]=[...(state.messages[key]||[]),{mine:true,text},{mine:false,text:'That sounds good! We can use the example dates and pickup point shown here. This is an automated demo reply.'}];state.rentalDraft=null;saveState();render();const list=document.getElementById('chat-messages');list.scrollTop=list.scrollHeight;document.getElementById('message-input').focus({preventScroll:true});
  }
  if(form.id==='survey-form'){event.preventDefault();captureSurvey(form);const session=surveySessions[activeSurvey];const q=SURVEY_QUESTIONS[session.step];const answer=session.answers[session.step];if(!q.optional&&(!answer||Array.isArray(answer)&&!answer.length)){const error=document.getElementById('survey-error');error.textContent='Choose at least one answer to continue.';error.hidden=false;return;}if(session.step===4)session.complete=true;else session.step++;updateSurvey();}
});
